### ISSUE TITLE
Class grade percentage decimal display

### ISSUE THREAD

**Issue by Crystalflxme** [sas-fossdev/saspes#191]
**Extension Version**: Most recent (Beta 0.21.3)

In the settings on the extension, there should be a feature where you can select how many decimal places you want to be displayed on your class grade percent. I also got an email about if this feature could be added, so I'm creating this issue.

For now, I think the glass grade percentage should display to 3 decimal places and in the future, should be a setting.

**Comment by Crystalflxme** [comment]
@gary-kim I'm looking into making a pull request. In the context of your code, how would you go about adding a setting? Also, where is the JS script for managing the display of the grade percentage setting?

**Comment by gary-kim** [comment]
There are a couple people who are familiar with this codebase so you don't have to ping me specifically :smile:. 

One quick thing, you're talking about the final percent display, right? I believe that may not be possible to change because we're pulling from the final percent from the comment in the page but that usually only contains the final percent to two decimal places.

Regardless, they are shown in the following places:

https://github.com/gary-kim/saspes/blob/1a2ccd80b557e7dd3f9f4014a15faf4907899ae1/src/js/components/ClassGrade.vue#L40-L42
https://github.com/gary-kim/saspes/blob/1a2ccd80b557e7dd3f9f4014a15faf4907899ae1/src/js/saspowerschoolff.js#L189-L193

**Comment by Crystalflxme** [comment]
Thanks for the info! Could you elaborate on where you source the final percent?

**Comment by gary-kim** [comment]
Try going to the class page and running the following in your browser console:
```javascript
document.querySelector('table.linkDescList').innerHTML;
```
